

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: spring-petclinic
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env: 
          - 
            name: MYSQL_DATABASE
            valueFrom: 
              configMapKeyRef: 
                key: mysql-database
                name: petclinic-config
          - 
            name: MYSQL_USER
            valueFrom: 
              secretKeyRef: 
                key: mysql-username
                name: mysql-secret
          - 
            name: MYSQL_PASSWORD
            valueFrom: 
              secretKeyRef: 
                key: mysql-password
                name: mysql-secret
          - 
            name: MYSQL_ROOT_PASSWORD
            valueFrom: 
              secretKeyRef: 
                key: mysql-root-password
                name: mysql-secret
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim


