apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: spring-petclinic
type: Opaque
data:
  mysql-username: cGV0dXNlcg==
  mysql-password: cGV0Y2xpbmlj
  mysql-root-password: cGV0Y2xpbmlj
