---

all:  
  hosts:
    local_machine:
      ansible_host: 127.0.0.1
      ansible_connection: local

  children:
    backend_machines:
      hosts:
        backend:
          ansible_user: wus
          ansible_ssh_host: '20.223.232.197'
          public_ip: '20.223.232.197'
          private_ip: '10.0.0.4'
          app_port: 9966
    frontend_machines:
      hosts:
        nginx:
          ansible_user: wus
          ansible_ssh_host: '20.223.232.197'
          public_ip: '20.223.232.197'
          private_ip: '10.0.0.4'
          app_port: 80
    database_machines:
      hosts:
        database:
          ansible_user: wus
          ansible_ssh_host: '20.223.232.197'
          public_ip: '20.223.232.197'
          private_ip: '10.0.0.4'
          app_port: 3306
          db_username: 'petclinic'
          db_password: 'petclinic'
          repl_user: 'replicant'
          repl_pass: 'replicant'
          mysql_root_pass: Qwerty!@#123